# Site settings
title: EpicDrive
tag_text: Super media network
description: A internet-connected cloud-powered media network by Gideon Tong
url: "https://epicdrive.gideontong.com"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
