# Site settings
title: Programming Resources
tag_text: &lt;Resources /&gt;
description: Programming resources for learning something new
url: "https://resources.gideontong.com"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
